version: '3.7'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

  grpc-service:
    build: 
      context: ./grpc-service
      dockerfile: Dockerfile
    container_name: grpc_service
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb

  http-service:
    build:
      context: ./http-service
      dockerfile: Dockerfile
    container_name: http_service
    depends_on:
      - grpc-service
    ports:
      - "8080:8080"

volumes:
  db_data:
